id: avita_domus_as_sb_10w_5c_rgbcct_10_watt_light_bulb
name: Avita Domus AS-SB-10W-5C RGBCCT 10 Watt Light Bulb
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: generic-bk7231t-qfn32-tuya
hardware:
  connectivity:
  - wifi
images:
- images/avita_domus_AS-SB-10W-5C.jpg
- images/tuya_firmware_version.png
- images/led_pcb.jpg
- images/main_pcb_top.jpg
- images/main_pcb_bottom.jpg
- images/wb3l_wifi_module.jpg
- images/programmin.jpg
- images/bulb_without_cup.jpg
docs_url: https://devices.esphome.io/devices/Avita-Domus-AS-SB-10W-5C-RGBCCT-10-Watt-Light-Bulb/
product_url: https://github.com/kprasadvnsi/Avita_Domus_AS-SB-10W-5C_RGBCCT_10Watt_Light_Bulb-esphome
featured_components:
- id: light_rgbct_1
  component_id: light.rgbct
  fields:
    color_interlock: true
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    red: output_red
    green: output_green
    blue: output_blue
    white_brightness: output_brightness
    color_temperature: output_temperature
    id: light_rgbct_1
    name: Light
- id: output_libretiny_pwm_1
  component_id: output.libretiny_pwm
  fields:
    inverted:
      value: true
      locked: true
    id: output_libretiny_pwm_1
source:
  type: esphome-devices
  remote_id: Avita-Domus-AS-SB-10W-5C-RGBCCT-10-Watt-Light-Bulb
  upstream_url: https://github.com/esphome/esphome-devices/blob/main/src/docs/devices/Avita-Domus-AS-SB-10W-5C-RGBCCT-10-Watt-Light-Bulb/index.md
  upstream_revision: 7fa250835bc3d3a2b319dced285d5e0c27171bd1
  content_hash: 9a78007a7b2db87bfa29d26f01833f589c7db1999f54d7192ce4f0a722fd6e23
