id: generic_rp2350
name: RP2350
description: Board by Generic with 16MB flash, 150MHz.
manufacturer: Generic
esphome:
  platform: rp2040
  board: generic_rp2350
  framework: arduino
hardware:
  flash_size: 16MB
  ram_size: 524288
  cpu_frequency: 150MHz
tags: []
docs_url: https://esphome.io/components/rp2040.html
product_url: https://www.raspberrypi.org/products/raspberry-pi-pico/
pins:
- gpio: 0
  label: GPIO0
  features:
  - pwm
  - i2c_sda
  - uart_tx
  available: null
  notes: Default I2C0 SDA, Default UART0 TX
- gpio: 1
  label: GPIO1
  features:
  - pwm
  - i2c_scl
  - uart_rx
  available: null
  notes: Default I2C0 SCL, Default UART0 RX
- gpio: 2
  label: GPIO2
  features:
  - pwm
  - spi_clk
  available: null
  notes: Default SPI0 CLK
- gpio: 3
  label: GPIO3
  features:
  - pwm
  - spi_mosi
  available: null
  notes: Default SPI0 MOSI (TX)
- gpio: 4
  label: GPIO4
  features:
  - pwm
  - spi_miso
  available: null
  notes: Default SPI0 MISO (RX)
- gpio: 5
  label: GPIO5
  features:
  - pwm
  - spi_cs
  available: null
  notes: Default SPI0 CS
- gpio: 6
  label: GPIO6
  features:
  - pwm
  available: null
- gpio: 7
  label: GPIO7
  features:
  - pwm
  available: null
- gpio: 8
  label: GPIO8
  features:
  - pwm
  available: null
- gpio: 9
  label: GPIO9
  features:
  - pwm
  available: null
- gpio: 10
  label: GPIO10
  features:
  - pwm
  available: null
- gpio: 11
  label: GPIO11
  features:
  - pwm
  available: null
- gpio: 12
  label: GPIO12
  features:
  - pwm
  available: null
- gpio: 13
  label: GPIO13
  features:
  - pwm
  available: null
- gpio: 14
  label: GPIO14
  features:
  - pwm
  available: null
- gpio: 15
  label: GPIO15
  features:
  - pwm
  available: null
- gpio: 16
  label: GPIO16
  features:
  - pwm
  available: null
- gpio: 17
  label: GPIO17
  features:
  - pwm
  available: null
- gpio: 18
  label: GPIO18
  features:
  - pwm
  available: null
- gpio: 19
  label: GPIO19
  features:
  - pwm
  available: null
- gpio: 20
  label: GPIO20
  features:
  - pwm
  available: null
- gpio: 21
  label: GPIO21
  features:
  - pwm
  available: null
- gpio: 22
  label: GPIO22
  features:
  - pwm
  available: null
- gpio: 23
  label: GPIO23
  features:
  - pwm
  available: null
- gpio: 24
  label: GPIO24
  features:
  - pwm
  available: null
- gpio: 25
  label: GPIO25
  features:
  - pwm
  available: null
- gpio: 26
  label: GPIO26
  features:
  - pwm
  available: null
- gpio: 27
  label: GPIO27
  features:
  - pwm
  available: null
- gpio: 28
  label: GPIO28
  features:
  - pwm
  available: null
- gpio: 29
  label: GPIO29
  features:
  - pwm
  available: null
- gpio: 30
  label: GPIO30
  features:
  - pwm
  available: null
- gpio: 31
  label: GPIO31
  features:
  - pwm
  available: null
- gpio: 32
  label: GPIO32
  features:
  - pwm
  available: null
- gpio: 33
  label: GPIO33
  features:
  - pwm
  available: null
- gpio: 34
  label: GPIO34
  features:
  - pwm
  available: null
- gpio: 35
  label: GPIO35
  features:
  - pwm
  available: null
- gpio: 36
  label: GPIO36
  features:
  - pwm
  available: null
- gpio: 37
  label: GPIO37
  features:
  - pwm
  available: null
- gpio: 38
  label: GPIO38
  features:
  - pwm
  available: null
- gpio: 39
  label: GPIO39
  features:
  - pwm
  available: null
- gpio: 40
  label: GPIO40
  features:
  - adc
  - pwm
  available: null
  notes: ADC0
- gpio: 41
  label: GPIO41
  features:
  - adc
  - pwm
  available: null
  notes: ADC1
- gpio: 42
  label: GPIO42
  features:
  - adc
  - pwm
  available: null
  notes: ADC2
- gpio: 43
  label: GPIO43
  features:
  - adc
  - pwm
  available: null
  notes: ADC3
- gpio: 44
  label: GPIO44
  features:
  - adc
  - pwm
  available: null
  notes: ADC4
- gpio: 45
  label: GPIO45
  features:
  - adc
  - pwm
  available: null
  notes: ADC5
- gpio: 46
  label: GPIO46
  features:
  - adc
  - pwm
  available: null
  notes: ADC6
- gpio: 47
  label: GPIO47
  features:
  - adc
  - pwm
  available: null
  notes: ADC7
