id: generic_2ch_wifi_curtain_module
name: Generic 2CH Wifi Curtain Module
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: generic-bk7231n-qfn32-tuya
hardware:
  connectivity:
  - wifi
images:
- images/device.jpg
- images/inside.jpg
docs_url: https://devices.esphome.io/devices/Generic-2CH-Wifi-Curtain-Module/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    device_class: running
    internal: true
    id: binary_sensor_gpio_1
    name: Gpio 1
- id: binary_sensor_gpio_2
  component_id: binary_sensor.gpio
  fields:
    device_class: running
    internal: true
    id: binary_sensor_gpio_2
    name: Gpio 2
- id: binary_sensor_gpio_3
  component_id: binary_sensor.gpio
  fields:
    device_class: running
    internal: true
    id: binary_sensor_gpio_3
    name: Gpio 3
- id: binary_sensor_gpio_4
  component_id: binary_sensor.gpio
  fields:
    device_class: running
    internal: true
    id: binary_sensor_gpio_4
    name: Gpio 4
- id: cover_time_based_1
  component_id: cover.time_based
  fields:
    device_class: shutter
    has_built_in_endstop: false
    open_duration: 40s
    close_duration: 36s
    assumed_state: true
    id: cover_time_based_1
    name: left-cover
- id: cover_time_based_2
  component_id: cover.time_based
  fields:
    device_class: shutter
    has_built_in_endstop: false
    open_duration: 40s
    close_duration: 36s
    assumed_state: true
    id: cover_time_based_2
    name: right-cover
- id: switch_gpio_1
  component_id: switch.gpio
  fields:
    restore_mode: ALWAYS_OFF
    internal: true
    id: switch_gpio_1
    name: Cover1_open
- id: switch_gpio_2
  component_id: switch.gpio
  fields:
    restore_mode: ALWAYS_OFF
    internal: true
    id: switch_gpio_2
    name: Cover1_close
- id: switch_gpio_3
  component_id: switch.gpio
  fields:
    restore_mode: ALWAYS_OFF
    internal: true
    id: switch_gpio_3
    name: Cover2_open
- id: switch_gpio_4
  component_id: switch.gpio
  fields:
    restore_mode: ALWAYS_OFF
    internal: true
    id: switch_gpio_4
    name: Cover2_close
source:
  type: esphome-devices
  remote_id: Generic-2CH-Wifi-Curtain-Module
  upstream_url: https://github.com/esphome/esphome-devices/blob/main/src/docs/devices/Generic-2CH-Wifi-Curtain-Module/index.md
  upstream_revision: 7fa250835bc3d3a2b319dced285d5e0c27171bd1
  content_hash: 29a66255ec94efe299c0dd476793d68886c0229a86dabd166741a090ee33d7bf
