id: loratap_sc500w
name: LoraTap SC500W
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp01_1m
hardware:
  connectivity:
  - wifi
images:
- images/LoraTap-SC500W.png
tags:
- relay
pins:
- gpio: 4
  available: false
  occupied_by: binary_sensor.gpio (${friendly_name} S1 switch input)
- gpio: 5
  available: false
  occupied_by: binary_sensor.gpio (${friendly_name} S2 switch input)
- gpio: 12
  available: false
  occupied_by: output.gpio (relay1)
- gpio: 13
  available: false
  occupied_by: binary_sensor.gpio (${friendly_name} button)
- gpio: 14
  available: false
  occupied_by: output.gpio (relay2)
docs_url: https://devices.esphome.io/devices/LoraTap-SC500W/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value: 13
      locked: true
    internal: true
    id: binary_sensor_gpio_1
    name: Gpio 1
- id: binary_sensor_gpio_2
  component_id: binary_sensor.gpio
  fields:
    pin:
      value: 4
      locked: true
    disabled_by_default: true
    id: binary_sensor_gpio_2
    name: Gpio 2
- id: binary_sensor_gpio_3
  component_id: binary_sensor.gpio
  fields:
    pin:
      value: 5
      locked: true
    disabled_by_default: true
    id: binary_sensor_gpio_3
    name: Gpio 3
- id: light_binary_1
  component_id: light.binary
  fields:
    output: relay1
    id: light_binary_1
    name: Binary 1
- id: light_binary_2
  component_id: light.binary
  fields:
    output: relay2
    id: light_binary_2
    name: Binary 2
- id: output_gpio_1
  component_id: output.gpio
  fields:
    pin:
      value: 12
      locked: true
    id: output_gpio_1
- id: output_gpio_2
  component_id: output.gpio
  fields:
    pin:
      value: 14
      locked: true
    id: output_gpio_2
- id: sensor_wifi_signal_1
  component_id: sensor.wifi_signal
  fields:
    update_interval: 60s
    id: sensor_wifi_signal_1
    name: Wifi Signal 1
source:
  type: esphome-devices
  remote_id: LoraTap-SC500W
  upstream_url: https://github.com/esphome/esphome-devices/blob/main/src/docs/devices/LoraTap-SC500W/index.md
  upstream_revision: 7fa250835bc3d3a2b319dced285d5e0c27171bd1
  content_hash: fd330abaaa1bd8fbab4be9fd14fb9ed532a55d7a6df6a0b0108e59e837b0c6de
