id: ledds
name: LEDDs v2
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework: esp-idf
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/LEDDs/ledds-on-front-1440p.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/LEDDs/enclosure-pcb-side-angle-1440p.jpg
docs_url: https://devices.esphome.io/devices/LEDDs/
product_url: https://github.com/VasilKalchev/LEDDs
featured_components:
- id: restart_button
  component_id: button.restart
  fields:
    entity_category: config
    device_class: restart
    id: restart_button
    name: Restart
- id: text_sensor_version_1
  component_id: text_sensor.version
  fields:
    hide_timestamp: true
    id: text_sensor_version_1
    name: ESPHome version
source:
  type: esphome-devices
  remote_id: LEDDs
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/LEDDs/index.md
  upstream_revision: a3fac0e48920548cbdce5fc00cb8b05571b4d83e
  content_hash: f596f4db92842e67c67c2594c229a672d4cd331f6c4e1ac588406ab90497146e
