id: mq_7
name: MQ-7 Carbon Monoxide Sensor
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32dev
  variant: esp32
  framework: arduino
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/MQ-7/mq-7.png
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/MQ-7/mq-7-heater-mod.webp
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/MQ-7/mq-7-device.png
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/MQ-7/mq-7-history.png
docs_url: https://devices.esphome.io/devices/MQ-7/
featured_components:
- id: temperature_sensor_id
  component_id: sensor.homeassistant
  fields:
    entity_id: sensor.temperature
    id: temperature_sensor_id
    name: Homeassistant 1
- id: humidity_sensor_id
  component_id: sensor.homeassistant
  fields:
    entity_id: sensor.humidity
    id: humidity_sensor_id
    name: Homeassistant 2
source:
  type: esphome-devices
  remote_id: MQ-7
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/MQ-7/index.md
  upstream_revision: a3fac0e48920548cbdce5fc00cb8b05571b4d83e
  content_hash: e35968370228cd3d9112ae670e2f82f3570b94956fbccdc3f39a614a5b349d17
