id: tuya_smart_plug_16a_il
name: Tuya Smart Plug 16A IL
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: cb2s
hardware:
  connectivity:
  - wifi
images:
- images/tuya-smart-plug-16A-IL-front.png
- images/tuya-smart-plug-16A-IL-back.png
- images/tuya-smart-plug-16A-IL-dissasemble.png
- images/tuya-smart-plug-16A-IL-breakout.png
- images/tuya-smart-plug-16A-IL-flasher.png
tags:
- relay
- compact
docs_url: https://devices.esphome.io/devices/Tuya-Smart-Plug-16A-IL/
featured_components:
- id: button_led
  component_id: output.gpio
  fields:
    inverted:
      value: true
      locked: true
    id: button_led
- id: sensor_hlw8012_1
  component_id: sensor.hlw8012
  fields:
    model: BL0937
    voltage_divider: 800
    current_resistor: 0.001 ohm
    update_interval: 1s
    change_mode_every: 1
    id: sensor_hlw8012_1
    name: Hlw8012 1
- id: relay
  component_id: switch.gpio
  fields:
    restore_mode: RESTORE_DEFAULT_OFF
    id: relay
    name: Relay Switch
source:
  type: esphome-devices
  remote_id: Tuya-Smart-Plug-16A-IL
  upstream_url: https://github.com/esphome/esphome-devices/blob/main/src/docs/devices/Tuya-Smart-Plug-16A-IL/index.md
  upstream_revision: 2bf64e131a2f72a0fc161c1f2f7d4de85c87a900
  content_hash: b0a725c8b9695555a8250ba0db8a5c622b0abad1e23fcc732b94b41871a92fb7
