"""
Tests for the per-installation peer-link X25519 identity helper.

Covers the lazy-create / load round-trip, the corrupted-on-disk
recovery path (regeneration), the rotation contract (different
pubkey, different pin), and the strict file-permission posture
that keeps the secret half off other users on the host.
"""

from __future__ import annotations

import asyncio
import hashlib
import sys
import threading
from pathlib import Path
from unittest.mock import patch

import pytest
from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey

from esphome_device_builder.helpers import peer_link_identity as identitymod
from esphome_device_builder.helpers.peer_link_identity import (
    _KEY_FILENAME,
    _KEY_LENGTH,
    _KEY_MODE,
    PeerLinkIdentity,
    PeerLinkIdentityStore,
    _log_loaded_identity,
)


async def test_first_call_creates_keyfile_with_correct_length(tmp_path: Path) -> None:
    """Lazy-create on first call produces a 32-byte key file."""
    key_path = tmp_path / _KEY_FILENAME
    assert not key_path.exists()
    identity = await PeerLinkIdentityStore(tmp_path).async_load()
    assert key_path.exists()
    assert len(key_path.read_bytes()) == _KEY_LENGTH
    assert identity.private_bytes == key_path.read_bytes()


async def test_second_call_reloads_same_identity(tmp_path: Path) -> None:
    """Subsequent calls return the same private + public bytes."""
    first = await PeerLinkIdentityStore(tmp_path).async_load()
    second = await PeerLinkIdentityStore(tmp_path).async_load()
    assert first.private_bytes == second.private_bytes
    assert first.public_bytes == second.public_bytes
    assert first.pin_sha256 == second.pin_sha256


@pytest.mark.skipif(sys.platform == "win32", reason="POSIX file modes only")
async def test_keyfile_has_strict_perms(tmp_path: Path) -> None:
    """Key file must be readable only by the owner; same shape as the cert key."""
    await PeerLinkIdentityStore(tmp_path).async_load()
    key_path = tmp_path / _KEY_FILENAME
    assert key_path.stat().st_mode & 0o777 == _KEY_MODE


async def test_pin_sha256_matches_pubkey_hash(tmp_path: Path) -> None:
    """``pin_sha256`` is the lowercase-hex SHA-256 of the public bytes."""
    identity = await PeerLinkIdentityStore(tmp_path).async_load()
    expected = hashlib.sha256(identity.public_bytes).hexdigest()
    assert identity.pin_sha256 == expected
    assert len(identity.pin_sha256) == 64
    assert identity.pin_sha256 == identity.pin_sha256.lower()


async def test_pin_sha256_formatted_groups_bytes_with_spaces(tmp_path: Path) -> None:
    identity = await PeerLinkIdentityStore(tmp_path).async_load()
    parts = identity.pin_sha256_formatted.split(" ")
    # 64 hex chars / 2 chars per byte = 32 byte groups
    assert len(parts) == 32
    assert all(len(p) == 2 for p in parts)


async def test_pubkey_round_trips_through_x25519(tmp_path: Path) -> None:
    """The persisted private bytes parse cleanly as X25519 + the pubkey is consistent."""
    identity = await PeerLinkIdentityStore(tmp_path).async_load()
    derived_pub = (
        X25519PrivateKey.from_private_bytes(identity.private_bytes).public_key().public_bytes_raw()
    )
    assert derived_pub == identity.public_bytes


async def test_two_different_dirs_get_different_keys(tmp_path: Path) -> None:
    dir_a = tmp_path / "a"
    dir_b = tmp_path / "b"
    dir_a.mkdir()
    dir_b.mkdir()
    a = await PeerLinkIdentityStore(dir_a).async_load()
    b = await PeerLinkIdentityStore(dir_b).async_load()
    assert a.private_bytes != b.private_bytes
    assert a.pin_sha256 != b.pin_sha256


async def test_rotation_replaces_keypair(tmp_path: Path) -> None:
    """``async_rotate`` writes a fresh keypair; pin changes."""
    before = await PeerLinkIdentityStore(tmp_path).async_load()
    after = await PeerLinkIdentityStore(tmp_path).async_rotate()
    assert before.private_bytes != after.private_bytes
    assert before.pin_sha256 != after.pin_sha256
    # Subsequent reload sees the rotated key.
    reloaded = await PeerLinkIdentityStore(tmp_path).async_load()
    assert reloaded.private_bytes == after.private_bytes


async def test_corrupted_keyfile_wrong_length_is_regenerated(tmp_path: Path) -> None:
    """A truncated key file is treated as missing; regeneration produces a usable identity."""
    key_path = tmp_path / _KEY_FILENAME
    # Write 16 bytes (half a real key); will fail the length check.
    key_path.write_bytes(b"\x00" * 16)
    identity = await PeerLinkIdentityStore(tmp_path).async_load()
    assert len(identity.private_bytes) == _KEY_LENGTH
    # The file on disk now has the regenerated bytes.
    assert key_path.read_bytes() == identity.private_bytes


async def test_unreadable_keyfile_falls_back_to_regeneration(tmp_path: Path) -> None:
    """
    OSError on read routes to the regenerate path.

    Permission denied or transient I/O are handled the same way as
    a missing or wrong-length file: the helper logs a warning but
    does not raise. Simulated by patching ``Path.read_bytes`` to
    fail (avoids platform-specific perm shenanigans).
    """
    key_path = tmp_path / _KEY_FILENAME
    key_path.write_bytes(b"\x00" * _KEY_LENGTH)  # plausible-looking key

    original_read_bytes = Path.read_bytes

    def _failing_read_bytes(self: Path) -> bytes:
        if self == key_path:
            raise OSError("simulated permission denied")
        return original_read_bytes(self)

    with patch.object(Path, "read_bytes", _failing_read_bytes):
        identity = await PeerLinkIdentityStore(tmp_path).async_load()

    # The helper recovered by regenerating; resulting identity is
    # usable end-to-end (real bytes parse as X25519, pin is the
    # SHA-256 of the derived pubkey).
    assert len(identity.private_bytes) == _KEY_LENGTH
    assert identity.pin_sha256 == hashlib.sha256(identity.public_bytes).hexdigest()
    # The on-disk file now has the regenerated bytes (the patch is
    # gone by the time we re-read here).
    assert key_path.read_bytes() == identity.private_bytes


async def test_async_load_serialised_under_asyncio_lock(tmp_path: Path) -> None:
    """Concurrent ``async_load`` calls share a single disk read."""
    store = PeerLinkIdentityStore(tmp_path)
    real_load = store._load_blocking
    load_calls = 0

    def _counting_load() -> PeerLinkIdentity:
        nonlocal load_calls
        load_calls += 1
        return real_load()

    with patch.object(store, "_load_blocking", _counting_load):
        results = await asyncio.gather(*(store.async_load() for _ in range(8)))

    assert len({identity.private_bytes for identity in results}) == 1
    assert load_calls == 1


async def test_async_load_waits_for_in_flight_async_rotate(tmp_path: Path) -> None:
    """A load racing a rotation observes the post-rotate identity, not the cached one."""
    store = PeerLinkIdentityStore(tmp_path)
    initial = await store.async_load()

    real_rotate = store._rotate_blocking
    rotate_started = threading.Event()
    rotate_release = threading.Event()

    def _slow_rotate() -> PeerLinkIdentity:
        rotate_started.set()
        # Block the executor thread until the test releases it,
        # so the asyncio.Lock stays held while the racing
        # ``async_load`` tries to acquire.
        rotate_release.wait(timeout=5.0)
        return real_rotate()

    with patch.object(store, "_rotate_blocking", _slow_rotate):
        rotate_task = asyncio.create_task(store.async_rotate())
        # Wait for the executor hop to start (lock now held).
        await asyncio.get_running_loop().run_in_executor(None, rotate_started.wait, 5.0)
        load_task = asyncio.create_task(store.async_load())
        # Give the loader a chance to acquire — it must not, because
        # the rotation holds the asyncio.Lock.
        await asyncio.sleep(0.05)
        assert not load_task.done()
        rotate_release.set()
        rotated, loaded = await asyncio.gather(rotate_task, load_task)

    assert rotated.private_bytes != initial.private_bytes
    assert loaded.private_bytes == rotated.private_bytes


async def test_cancelled_first_async_load_still_populates_cache(tmp_path: Path) -> None:
    """A cancelled first-time generator still lands a single key on disk + cache."""
    store = PeerLinkIdentityStore(tmp_path)

    real_load = store._load_blocking
    load_started = threading.Event()
    load_release = threading.Event()
    load_call_count = 0
    landed: list[PeerLinkIdentity] = []

    def _slow_load() -> PeerLinkIdentity:
        nonlocal load_call_count
        load_call_count += 1
        load_started.set()
        load_release.wait(timeout=5.0)
        identity = real_load()
        landed.append(identity)
        return identity

    with patch.object(store, "_load_blocking", _slow_load):
        first = asyncio.create_task(store.async_load())
        await asyncio.get_running_loop().run_in_executor(None, load_started.wait, 5.0)
        first.cancel()
        with pytest.raises(asyncio.CancelledError):
            await first
        load_release.set()
        for _ in range(50):
            if landed:
                break
            await asyncio.sleep(0.01)
        assert landed, "executor never completed"
        cached_after = await store.async_load()

    assert cached_after.private_bytes == landed[0].private_bytes
    # Only the original generator ran; the post-cancel load hit
    # the populated cache.
    assert load_call_count == 1


async def test_cancelled_async_rotate_keeps_cache_consistent_with_disk(tmp_path: Path) -> None:
    """A cancelled rotation still updates the cache to match the on-disk key."""
    store = PeerLinkIdentityStore(tmp_path)
    initial = await store.async_load()

    real_rotate = store._rotate_blocking
    rotate_started = threading.Event()
    rotate_release = threading.Event()
    rotated_identity: list[PeerLinkIdentity] = []

    def _slow_rotate() -> PeerLinkIdentity:
        rotate_started.set()
        rotate_release.wait(timeout=5.0)
        identity = real_rotate()
        rotated_identity.append(identity)
        return identity

    with patch.object(store, "_rotate_blocking", _slow_rotate):
        rotate_task = asyncio.create_task(store.async_rotate())
        await asyncio.get_running_loop().run_in_executor(None, rotate_started.wait, 5.0)
        rotate_task.cancel()
        with pytest.raises(asyncio.CancelledError):
            await rotate_task
        rotate_release.set()
        # Wait for the shielded background rotation to finish so
        # the cache update lands before we assert.
        for _ in range(50):
            if rotated_identity:
                break
            await asyncio.sleep(0.01)
        assert rotated_identity, "executor never completed"

    after = await store.async_load()
    assert after.private_bytes == rotated_identity[0].private_bytes
    assert after.private_bytes != initial.private_bytes


async def test_returns_peer_link_identity_dataclass(tmp_path: Path) -> None:
    """Sanity: the public API returns the documented dataclass shape."""
    identity = await PeerLinkIdentityStore(tmp_path).async_load()
    assert isinstance(identity, PeerLinkIdentity)
    # The dataclass is frozen, attempting to mutate raises.
    with pytest.raises((AttributeError, TypeError)):  # frozen dataclass
        identity.private_bytes = b"replacement"  # type: ignore[misc]


async def test_loaded_identity_log_carries_pubkey_and_file_stat(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    """Every load logs the key-file path, size, mtime, raw pubkey hex, and pin."""
    with caplog.at_level("INFO", logger=identitymod.__name__):
        identity = await PeerLinkIdentityStore(tmp_path).async_load()

    key_path = tmp_path / _KEY_FILENAME
    records = [
        rec for rec in caplog.records if "Loaded peer-link identity from" in rec.getMessage()
    ]
    assert len(records) == 1
    msg = records[0].getMessage()
    assert str(key_path) in msg
    assert f"size={_KEY_LENGTH}" in msg
    assert f"pub={identity.public_bytes.hex()}" in msg
    assert f"pin={identity.pin_sha256}" in msg


def test_loaded_identity_log_marks_stat_failure(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    """When ``stat()`` fails the log carries an explicit ``stat_failed`` marker."""
    key_path = tmp_path / "missing-on-purpose.bin"
    pub = b"\x11" * 32
    pin = hashlib.sha256(pub).hexdigest()

    with caplog.at_level("INFO", logger=identitymod.__name__):
        _log_loaded_identity(key_path, pub, pin)

    records = [
        rec for rec in caplog.records if "Loaded peer-link identity from" in rec.getMessage()
    ]
    assert len(records) == 1
    msg = records[0].getMessage()
    # File doesn't exist → ``stat()`` raises FileNotFoundError;
    # operator sees ``stat_failed: ...`` instead of misleading
    # ``size=-1 mtime=0`` placeholders.
    assert "stat_failed: FileNotFoundError" in msg
    assert "size=" not in msg
    assert "mtime=" not in msg
    assert f"pub={pub.hex()}" in msg
    assert f"pin={pin}" in msg


async def test_loaded_identity_log_fires_on_rotate(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    """``async_rotate`` logs the new pubkey + pin after the write."""
    await PeerLinkIdentityStore(tmp_path).async_load()
    caplog.clear()
    with caplog.at_level("INFO", logger=identitymod.__name__):
        rotated = await PeerLinkIdentityStore(tmp_path).async_rotate()

    records = [
        rec for rec in caplog.records if "Loaded peer-link identity from" in rec.getMessage()
    ]
    assert len(records) == 1
    msg = records[0].getMessage()
    assert f"pub={rotated.public_bytes.hex()}" in msg
    assert f"pin={rotated.pin_sha256}" in msg


async def test_repeat_calls_hit_cache_and_log_only_once(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    """Sequential calls return the cached instance and don't re-log."""
    store = PeerLinkIdentityStore(tmp_path)
    with caplog.at_level("INFO", logger=identitymod.__name__):
        first = await store.async_load()
        second = await store.async_load()
        third = await store.async_load()

    assert first is second
    assert first is third
    load_records = [
        rec for rec in caplog.records if "Loaded peer-link identity from" in rec.getMessage()
    ]
    assert len(load_records) == 1


async def test_rotate_invalidates_cache(tmp_path: Path) -> None:
    """A post-rotate ``async_load`` returns the rotated identity (cache refreshed)."""
    store = PeerLinkIdentityStore(tmp_path)
    before = await store.async_load()
    rotated = await store.async_rotate()
    after = await store.async_load()
    assert before is not rotated
    assert after is rotated
