"""Tests for the Matrix-SAS pin-fingerprint emoji rendering helper."""

from __future__ import annotations

import re
import sys
from pathlib import Path

import pytest

from esphome_device_builder.helpers.pin_emoji import (
    PIN_EMOJI_COUNT,
    SAS_EMOJI,
    pin_emoji,
    pin_emoji_names,
    pin_emoji_slots,
)

# The built frontend bundle emits the SAS table minified as a run of
# ``{emoji:"🐶",name:"Dog"}`` object literals (emoji as literal
# glyphs, not ``\u{...}`` escapes). Extract them in order to compare
# against the backend port.
_BUNDLE_ENTRY_RE = re.compile(r'\{emoji:"([^"]+)",name:"([^"]+)"\}')


def _frontend_sas_table() -> tuple[tuple[str, str], ...] | None:
    """Extract the SAS ``(emoji, name)`` table from the installed frontend wheel.

    Returns ``None`` when the ``esphome-device-builder-frontend``
    package isn't installed (API-only deployments) — the caller
    skips rather than fails.
    """
    try:
        import esphome_device_builder_frontend as frontend  # noqa: PLC0415
    except ImportError:
        return None
    # ``app.<contenthash>.js`` carries the app code; the hash changes
    # every build, so glob rather than hardcode.
    app_bundles = sorted(Path(frontend.where()).glob("app.*.js"))
    if not app_bundles:
        return None
    source = app_bundles[0].read_text(encoding="utf-8")
    return tuple(_BUNDLE_ENTRY_RE.findall(source))


def test_table_matches_matrix_sas_shape() -> None:
    """
    Pin the table's shape: 64 unique entries, unique names, spec anchors.

    The vocabulary and order come from the Matrix SAS spec v1.x and
    must byte-match the frontend's ``src/util/pin-emoji.ts`` — the
    CLI banner and the ``esphome-pin-emoji-grid`` component render
    the same pin, and the operator compares them by eye.
    """
    assert len(SAS_EMOJI) == 64
    assert len({emoji for emoji, _ in SAS_EMOJI}) == 64
    assert len({name for _, name in SAS_EMOJI}) == 64
    # Spec anchor points: first, last, and a VS16-carrying entry.
    assert SAS_EMOJI[0] == ("\U0001f436", "Dog")
    assert SAS_EMOJI[21] == ("☁️", "Cloud")
    assert SAS_EMOJI[63] == ("\U0001f4cc", "Pin")


def test_known_vector_matches_frontend() -> None:
    """
    A frozen pin→emoji vector, generated by the frontend's TS implementation.

    ``pinSha256ToEmojis("8efd6168a055…")`` under node produced this
    sequence; the Python port must agree forever, or the CLI banner
    and the pair dialog stop matching mid-upgrade.
    """
    pin = "8efd6168a055d1e478190ffa9f1ea22f6a1b1f2f4914d3251daaeca9a3467d4c"
    slots = pin_emoji_slots(pin)
    assert [name for _, name in slots] == [
        "Santa",
        "Key",
        "Aeroplane",
        "Glasses",
        "Corn",
        "Penguin",
        "Cat",
    ]
    assert pin_emoji(pin) == "🎅 🔑 ✈️ 👓 🌽 🐧 🐱"
    assert pin_emoji_names(pin) == "Santa, Key, Aeroplane, Glasses, Corn, Penguin, Cat"


def test_uses_leading_42_bits_only() -> None:
    """Only the first 11 nibbles (44 bits, top 42 used) select emoji."""
    base = "00" * 32
    tail_differs = "00000000000" + "f" * 53
    assert pin_emoji_slots(base) == (SAS_EMOJI[0],) * PIN_EMOJI_COUNT
    assert pin_emoji(base) == pin_emoji(tail_differs)


def test_first_chunk_change_changes_output() -> None:
    """A leading-bits flip yields a different sequence."""
    assert pin_emoji("00" * 32) != pin_emoji("04" + "00" * 31)


def test_frontend_bundle_table_matches_backend() -> None:
    """
    Drift tripwire: the backend port must match the shipped frontend bundle.

    Reads the SAS ``(emoji, name)`` table out of the built
    ``esphome-device-builder-frontend`` wheel (the exact artifact the
    user's browser runs, pinned in this release — no network) and
    compares it, in order, against the backend port. A frontend
    change here is allowed, but this failure means the backend must
    be re-synced before the next release, or the CLI banner and the
    pair dialog stop rendering the same fingerprint for a given pin.

    Skips only when the frontend package isn't installed (API-only
    deployments); otherwise it always runs — no network, no flake.
    """
    table = _frontend_sas_table()
    if table is None:
        pytest.skip("esphome-device-builder-frontend not installed")
    assert len(table) == 64, "frontend SAS table changed size; re-sync the backend port"
    assert table == SAS_EMOJI


def test_frontend_sas_table_none_when_package_missing(monkeypatch: pytest.MonkeyPatch) -> None:
    """API-only installs (no frontend wheel) yield ``None`` so the tripwire skips."""
    monkeypatch.setitem(sys.modules, "esphome_device_builder_frontend", None)
    assert _frontend_sas_table() is None


def test_frontend_sas_table_none_when_no_bundle(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """A frontend dir with no ``app.*.js`` (broken/partial wheel) yields ``None``."""
    frontend = pytest.importorskip("esphome_device_builder_frontend")
    monkeypatch.setattr(frontend, "where", lambda: str(tmp_path))
    assert _frontend_sas_table() is None
