"""
Tests for the per-installation peer-link X25519 identity helper.

Covers the lazy-create / load round-trip, the corrupted-on-disk
recovery path (regeneration), the rotation contract (different
pubkey, different pin), and the strict file-permission posture
that keeps the secret half off other users on the host.
"""

from __future__ import annotations

import hashlib
import sys
import threading
from pathlib import Path
from unittest.mock import patch

import pytest
from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey

from esphome_device_builder.helpers import peer_link_identity as identitymod
from esphome_device_builder.helpers.peer_link_identity import (
    _KEY_FILENAME,
    _KEY_LENGTH,
    _KEY_MODE,
    PeerLinkIdentity,
    _log_loaded_identity,
    get_or_create_peer_link_identity,
    rotate_peer_link_identity,
)


def test_first_call_creates_keyfile_with_correct_length(tmp_path: Path) -> None:
    """Lazy-create on first call produces a 32-byte key file."""
    key_path = tmp_path / _KEY_FILENAME
    assert not key_path.exists()
    identity = get_or_create_peer_link_identity(tmp_path)
    assert key_path.exists()
    assert len(key_path.read_bytes()) == _KEY_LENGTH
    assert identity.private_bytes == key_path.read_bytes()


def test_second_call_reloads_same_identity(tmp_path: Path) -> None:
    """Subsequent calls return the same private + public bytes."""
    first = get_or_create_peer_link_identity(tmp_path)
    second = get_or_create_peer_link_identity(tmp_path)
    assert first.private_bytes == second.private_bytes
    assert first.public_bytes == second.public_bytes
    assert first.pin_sha256 == second.pin_sha256


@pytest.mark.skipif(sys.platform == "win32", reason="POSIX file modes only")
def test_keyfile_has_strict_perms(tmp_path: Path) -> None:
    """Key file must be readable only by the owner; same shape as the cert key."""
    get_or_create_peer_link_identity(tmp_path)
    key_path = tmp_path / _KEY_FILENAME
    assert key_path.stat().st_mode & 0o777 == _KEY_MODE


def test_pin_sha256_matches_pubkey_hash(tmp_path: Path) -> None:
    """``pin_sha256`` is the lowercase-hex SHA-256 of the public bytes."""
    identity = get_or_create_peer_link_identity(tmp_path)
    expected = hashlib.sha256(identity.public_bytes).hexdigest()
    assert identity.pin_sha256 == expected
    assert len(identity.pin_sha256) == 64
    assert identity.pin_sha256 == identity.pin_sha256.lower()


def test_pin_sha256_formatted_groups_bytes_with_spaces(tmp_path: Path) -> None:
    identity = get_or_create_peer_link_identity(tmp_path)
    parts = identity.pin_sha256_formatted.split(" ")
    # 64 hex chars / 2 chars per byte = 32 byte groups
    assert len(parts) == 32
    assert all(len(p) == 2 for p in parts)


def test_pubkey_round_trips_through_x25519(tmp_path: Path) -> None:
    """The persisted private bytes parse cleanly as X25519 + the pubkey is consistent."""
    identity = get_or_create_peer_link_identity(tmp_path)
    derived_pub = (
        X25519PrivateKey.from_private_bytes(identity.private_bytes).public_key().public_bytes_raw()
    )
    assert derived_pub == identity.public_bytes


def test_two_different_dirs_get_different_keys(tmp_path: Path) -> None:
    dir_a = tmp_path / "a"
    dir_b = tmp_path / "b"
    dir_a.mkdir()
    dir_b.mkdir()
    a = get_or_create_peer_link_identity(dir_a)
    b = get_or_create_peer_link_identity(dir_b)
    assert a.private_bytes != b.private_bytes
    assert a.pin_sha256 != b.pin_sha256


def test_rotation_replaces_keypair(tmp_path: Path) -> None:
    """``rotate_peer_link_identity`` writes a fresh keypair; pin changes."""
    before = get_or_create_peer_link_identity(tmp_path)
    after = rotate_peer_link_identity(tmp_path)
    assert before.private_bytes != after.private_bytes
    assert before.pin_sha256 != after.pin_sha256
    # Subsequent reload sees the rotated key.
    reloaded = get_or_create_peer_link_identity(tmp_path)
    assert reloaded.private_bytes == after.private_bytes


def test_corrupted_keyfile_wrong_length_is_regenerated(tmp_path: Path) -> None:
    """A truncated key file is treated as missing; regeneration produces a usable identity."""
    key_path = tmp_path / _KEY_FILENAME
    # Write 16 bytes (half a real key); will fail the length check.
    key_path.write_bytes(b"\x00" * 16)
    identity = get_or_create_peer_link_identity(tmp_path)
    assert len(identity.private_bytes) == _KEY_LENGTH
    # The file on disk now has the regenerated bytes.
    assert key_path.read_bytes() == identity.private_bytes


def test_unreadable_keyfile_falls_back_to_regeneration(tmp_path: Path) -> None:
    """
    OSError on read routes to the regenerate path.

    Permission denied or transient I/O are handled the same way as
    a missing or wrong-length file: the helper logs a warning but
    does not raise. Simulated by patching ``Path.read_bytes`` to
    fail (avoids platform-specific perm shenanigans).
    """
    key_path = tmp_path / _KEY_FILENAME
    key_path.write_bytes(b"\x00" * _KEY_LENGTH)  # plausible-looking key

    original_read_bytes = Path.read_bytes

    def _failing_read_bytes(self: Path) -> bytes:
        if self == key_path:
            raise OSError("simulated permission denied")
        return original_read_bytes(self)

    with patch.object(Path, "read_bytes", _failing_read_bytes):
        identity = get_or_create_peer_link_identity(tmp_path)

    # The helper recovered by regenerating; resulting identity is
    # usable end-to-end (real bytes parse as X25519, pin is the
    # SHA-256 of the derived pubkey).
    assert len(identity.private_bytes) == _KEY_LENGTH
    assert identity.pin_sha256 == hashlib.sha256(identity.public_bytes).hexdigest()
    # The on-disk file now has the regenerated bytes (the patch is
    # gone by the time we re-read here).
    assert key_path.read_bytes() == identity.private_bytes


def test_first_creation_is_serialised_under_lock(tmp_path: Path) -> None:
    """
    Multiple threads racing on a fresh dir must not both write a key.

    The lock + load-after-take pattern is load-bearing: without it,
    two callers each observe "no key file" inside ``_load_key``,
    each generate a fresh keypair, and the loser's atomic write
    silently overwrites the winner's bytes; different identities
    land on disk depending on the interleaving.

    Force the race with a :class:`threading.Barrier` so all workers
    reach the helper at the same instant, then assert exactly one
    write occurred and all callers observe identical bytes.
    """
    real_write = identitymod.atomic_write
    write_calls: list[Path] = []
    write_lock = threading.Lock()

    def _tracking_write(path: Path, data: bytes, *, mode: int = 0o644) -> None:
        with write_lock:
            write_calls.append(path)
        real_write(path, data, mode=mode)

    worker_count = 8
    barrier = threading.Barrier(worker_count)
    results: list[PeerLinkIdentity] = []
    results_lock = threading.Lock()

    def _worker() -> None:
        barrier.wait()
        identity = get_or_create_peer_link_identity(tmp_path)
        with results_lock:
            results.append(identity)

    with patch.object(identitymod, "atomic_write", _tracking_write):
        threads = [threading.Thread(target=_worker) for _ in range(worker_count)]
        for thread in threads:
            thread.start()
        for thread in threads:
            thread.join()

    # Exactly one thread won the lock and wrote; the rest reloaded.
    assert len(write_calls) == 1
    assert write_calls[0] == tmp_path / _KEY_FILENAME
    # All workers observed the same bytes; no winner-overwrite race.
    assert len(results) == worker_count
    assert len({identity.private_bytes for identity in results}) == 1


def test_returns_peer_link_identity_dataclass(tmp_path: Path) -> None:
    """Sanity: the public API returns the documented dataclass shape."""
    identity = get_or_create_peer_link_identity(tmp_path)
    assert isinstance(identity, PeerLinkIdentity)
    # The dataclass is frozen, attempting to mutate raises.
    with pytest.raises((AttributeError, TypeError)):  # frozen dataclass
        identity.private_bytes = b"replacement"  # type: ignore[misc]


def test_loaded_identity_log_carries_pubkey_and_file_stat(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    """Every load logs the key-file path, size, mtime, raw pubkey hex, and pin."""
    with caplog.at_level("INFO", logger=identitymod.__name__):
        identity = get_or_create_peer_link_identity(tmp_path)

    key_path = tmp_path / _KEY_FILENAME
    records = [
        rec for rec in caplog.records if "Loaded peer-link identity from" in rec.getMessage()
    ]
    assert len(records) == 1
    msg = records[0].getMessage()
    assert str(key_path) in msg
    assert f"size={_KEY_LENGTH}" in msg
    assert f"pub={identity.public_bytes.hex()}" in msg
    assert f"pin={identity.pin_sha256}" in msg


def test_loaded_identity_log_marks_stat_failure(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    """When ``stat()`` fails the log carries an explicit ``stat_failed`` marker."""
    key_path = tmp_path / "missing-on-purpose.bin"
    pub = b"\x11" * 32
    pin = hashlib.sha256(pub).hexdigest()

    with caplog.at_level("INFO", logger=identitymod.__name__):
        _log_loaded_identity(key_path, pub, pin)

    records = [
        rec for rec in caplog.records if "Loaded peer-link identity from" in rec.getMessage()
    ]
    assert len(records) == 1
    msg = records[0].getMessage()
    # File doesn't exist → ``stat()`` raises FileNotFoundError;
    # operator sees ``stat_failed: ...`` instead of misleading
    # ``size=-1 mtime=0`` placeholders.
    assert "stat_failed: FileNotFoundError" in msg
    assert "size=" not in msg
    assert "mtime=" not in msg
    assert f"pub={pub.hex()}" in msg
    assert f"pin={pin}" in msg


def test_loaded_identity_log_fires_on_rotate(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    """``rotate_peer_link_identity`` logs the new pubkey + pin after the write."""
    get_or_create_peer_link_identity(tmp_path)
    caplog.clear()
    with caplog.at_level("INFO", logger=identitymod.__name__):
        rotated = rotate_peer_link_identity(tmp_path)

    records = [
        rec for rec in caplog.records if "Loaded peer-link identity from" in rec.getMessage()
    ]
    assert len(records) == 1
    msg = records[0].getMessage()
    assert f"pub={rotated.public_bytes.hex()}" in msg
    assert f"pin={rotated.pin_sha256}" in msg
