"""Tests for the Matrix-SAS pin-fingerprint emoji rendering helper."""

from __future__ import annotations

import re
import urllib.error
import urllib.request

import pytest

from esphome_device_builder.helpers.pin_emoji import (
    PIN_EMOJI_COUNT,
    SAS_EMOJI,
    pin_emoji,
    pin_emoji_names,
    pin_emoji_slots,
)

_FRONTEND_PIN_EMOJI_URL = (
    "https://raw.githubusercontent.com/esphome/device-builder-frontend/main/src/util/pin-emoji.ts"
)

_TS_ENTRY_RE = re.compile(r'\{\s*emoji:\s*"((?:\\u\{[0-9A-Fa-f]+\})+)",\s*name:\s*"([^"]+)"\s*\}')
_TS_ESCAPE_RE = re.compile(r"\\u\{([0-9A-Fa-f]+)\}")


def _decode_ts_string(escaped: str) -> str:
    r"""Decode a TS ``\u{XXXX}`` escape sequence into the literal string."""
    return _TS_ESCAPE_RE.sub(lambda m: chr(int(m.group(1), 16)), escaped)


def test_table_matches_matrix_sas_shape() -> None:
    """
    Pin the table's shape: 64 unique entries, unique names, spec anchors.

    The vocabulary and order come from the Matrix SAS spec v1.x and
    must byte-match the frontend's ``src/util/pin-emoji.ts`` — the
    CLI banner and the ``esphome-pin-emoji-grid`` component render
    the same pin, and the operator compares them by eye.
    """
    assert len(SAS_EMOJI) == 64
    assert len({emoji for emoji, _ in SAS_EMOJI}) == 64
    assert len({name for _, name in SAS_EMOJI}) == 64
    # Spec anchor points: first, last, and a VS16-carrying entry.
    assert SAS_EMOJI[0] == ("\U0001f436", "Dog")
    assert SAS_EMOJI[21] == ("☁️", "Cloud")
    assert SAS_EMOJI[63] == ("\U0001f4cc", "Pin")


def test_known_vector_matches_frontend() -> None:
    """
    A frozen pin→emoji vector, generated by the frontend's TS implementation.

    ``pinSha256ToEmojis("8efd6168a055…")`` under node produced this
    sequence; the Python port must agree forever, or the CLI banner
    and the pair dialog stop matching mid-upgrade.
    """
    pin = "8efd6168a055d1e478190ffa9f1ea22f6a1b1f2f4914d3251daaeca9a3467d4c"
    slots = pin_emoji_slots(pin)
    assert [name for _, name in slots] == [
        "Santa",
        "Key",
        "Aeroplane",
        "Glasses",
        "Corn",
        "Penguin",
        "Cat",
    ]
    assert pin_emoji(pin) == "🎅 🔑 ✈️ 👓 🌽 🐧 🐱"
    assert pin_emoji_names(pin) == "Santa, Key, Aeroplane, Glasses, Corn, Penguin, Cat"


def test_uses_leading_42_bits_only() -> None:
    """Only the first 11 nibbles (44 bits, top 42 used) select emoji."""
    base = "00" * 32
    tail_differs = "00000000000" + "f" * 53
    assert pin_emoji_slots(base) == [SAS_EMOJI[0]] * PIN_EMOJI_COUNT
    assert pin_emoji(base) == pin_emoji(tail_differs)


def test_first_chunk_change_changes_output() -> None:
    """A leading-bits flip yields a different sequence."""
    assert pin_emoji("00" * 32) != pin_emoji("04" + "00" * 31)


def test_frontend_main_branch_table_matches_backend() -> None:
    """
    Cross-repo drift tripwire: the backend port must match the frontend's ``main``.

    Fetches ``src/util/pin-emoji.ts`` from the frontend repo's main
    branch and compares its SAS table (codepoints + names), default
    emoji count, and 6-bit-chunking markers against this port. A
    frontend change here is allowed — but this failure means the
    backend must be re-synced before the next release, or the CLI
    banner and pair dialog stop rendering the same fingerprint.
    Skips (rather than fails) when GitHub is unreachable so offline
    runs don't flake; CI provides the enforcement.
    """
    try:
        with urllib.request.urlopen(_FRONTEND_PIN_EMOJI_URL, timeout=15) as response:
            source = response.read().decode("utf-8")
    except (urllib.error.URLError, TimeoutError) as exc:
        pytest.skip(f"frontend repo unreachable: {exc}")

    entries = [(_decode_ts_string(emoji), name) for emoji, name in _TS_ENTRY_RE.findall(source)]
    assert tuple(entries) == SAS_EMOJI

    count_match = re.search(r"pinSha256ToEmojis\(pin: string, count = (\d+)\)", source)
    assert count_match is not None, "frontend changed pinSha256ToEmojis's signature; re-sync"
    assert int(count_match.group(1)) == PIN_EMOJI_COUNT

    # Algorithm markers: the nibble-fed 6-bit chunker. If these lines
    # change, the indexing may have too — re-verify the port against
    # the new TS (see the node cross-check in the PR that added this).
    assert "bits = (bits << 4) | nibble;" in source
    assert "& 0x3f;" in source
