id: maxcio_rmc020
name: Maxcio RMC020 IT
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp01_1m
hardware:
  connectivity:
  - wifi
images:
- images/MaxcioRMC020.jpg
- images/MaxcioRMC020retro.jpg
tags:
- relay
- compact
pins:
- gpio: 4
  available: false
  occupied_by: sensor.hlw8012
- gpio: 5
  available: false
  occupied_by: sensor.hlw8012
- gpio: 12
  available: false
  occupied_by: sensor.hlw8012
- gpio: 13
  available: false
  occupied_by: output.esp8266_pwm (${devicename}_red_output)
- gpio: 14
  available: false
  occupied_by: switch.gpio (${friendly_name})
docs_url: https://devices.esphome.io/devices/Maxcio-RMC020/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    device_class: power
    id: binary_sensor_gpio_1
    name: Gpio 1
- id: output_esp8266_pwm_1
  component_id: output.esp8266_pwm
  fields:
    pin:
      value:
        number: 13
        inverted: true
      locked: true
    id: output_esp8266_pwm_1
- id: sensor_wifi_signal_1
  component_id: sensor.wifi_signal
  fields:
    update_interval: 60s
    id: sensor_wifi_signal_1
    name: Wifi Signal 1
- id: sensor_hlw8012_1
  component_id: sensor.hlw8012
  fields:
    sel_pin:
      value:
        number: 12
        inverted: true
      locked: true
    cf_pin:
      value: 4
      locked: true
    cf1_pin:
      value: 5
      locked: true
    change_mode_every: 8
    update_interval: 10s
    id: sensor_hlw8012_1
    name: Hlw8012 1
- id: switch_gpio_1
  component_id: switch.gpio
  fields:
    pin:
      value: 14
      locked: true
    restore_mode: ALWAYS_OFF
    id: switch_gpio_1
    name: Gpio 1
source:
  type: esphome-devices
  remote_id: Maxcio-RMC020
  upstream_url: https://github.com/esphome/esphome-devices/blob/main/src/docs/devices/Maxcio-RMC020/index.md
  upstream_revision: 7fa250835bc3d3a2b319dced285d5e0c27171bd1
  content_hash: 8837481612b75328b64e2949e53e309544546e1971658c2e6bcd3a0fba04193a
