id: generic-bk7231n-qfn32-tuya
name: Generic - BK7231N (Tuya QFN32)
description: Generic - BK7231N (Tuya QFN32) (BK72XX board).
manufacturer: ''
is_generic: true
esphome:
  platform: bk72xx
  board: generic-bk7231n-qfn32-tuya
  framework: arduino
hardware:
  connectivity:
  - wifi
tags: []
docs_url: https://esphome.io/components/libretiny.html
pins: []
