id: shelly_rgbw2
name: Shelly RGBW2
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp01_1m
hardware:
  connectivity:
  - wifi
images:
- images/Shelly-RGBW2.png
tags:
- shelly
pins:
- gpio: 4
  available: false
  occupied_by: output.esp8266_pwm (pwm_w)
- gpio: 12
  available: false
  occupied_by: output.esp8266_pwm (pwm_r)
- gpio: 14
  available: false
  occupied_by: output.esp8266_pwm (pwm_b)
- gpio: 15
  available: false
  occupied_by: output.esp8266_pwm (pwm_g)
docs_url: https://devices.esphome.io/devices/Shelly-RGBW2/
featured_components:
- id: light_rgbw_1
  component_id: light.rgbw
  fields:
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    white: pwm_w
    id: light_rgbw_1
    name: ledstrip_shelly_rgbw2
- id: output_esp8266_pwm_1
  component_id: output.esp8266_pwm
  fields:
    pin:
      value: 12
      locked: true
    frequency: 1000 Hz
    id: output_esp8266_pwm_1
- id: output_esp8266_pwm_2
  component_id: output.esp8266_pwm
  fields:
    pin:
      value: 15
      locked: true
    frequency: 1000 Hz
    id: output_esp8266_pwm_2
- id: output_esp8266_pwm_3
  component_id: output.esp8266_pwm
  fields:
    pin:
      value: 14
      locked: true
    frequency: 1000 Hz
    id: output_esp8266_pwm_3
- id: output_esp8266_pwm_4
  component_id: output.esp8266_pwm
  fields:
    pin:
      value: 4
      locked: true
    frequency: 1000 Hz
    id: output_esp8266_pwm_4
source:
  type: esphome-devices
  remote_id: Shelly-RGBW2
  upstream_url: https://github.com/esphome/esphome-devices/blob/main/src/docs/devices/Shelly-RGBW2/index.md
  upstream_revision: 7fa250835bc3d3a2b319dced285d5e0c27171bd1
  content_hash: 3afb14d12a54eb51b21b3f69c4606f0e8460f0fcc8ce1f922799cdfa92ab2892
