id: kincony_dm8
name: KinCony-DM8 (ESP32-S3 8CH Dimmer board)
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32-s3-devkitc-1
  framework: arduino
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- images/DM8-1.jpg
pins:
- gpio: 0
  available: false
  occupied_by: binary_sensor.gpio (dm8-input01)
- gpio: 1
  available: false
  occupied_by: binary_sensor.gpio (dm8-input02)
- gpio: 2
  available: false
  occupied_by: binary_sensor.gpio (dm8-input03)
- gpio: 3
  available: false
  occupied_by: binary_sensor.gpio (dm8-input04)
- gpio: 4
  available: false
  occupied_by: binary_sensor.gpio (dm8-input05)
- gpio: 5
  available: false
  occupied_by: binary_sensor.gpio (dm8-input06)
- gpio: 6
  available: false
  occupied_by: binary_sensor.gpio (dm8-input07)
- gpio: 7
  available: false
  occupied_by: binary_sensor.gpio (dm8-input08)
- gpio: 13
  available: false
  occupied_by: binary_sensor.gpio (dm8-W1-io13)
- gpio: 14
  available: false
  occupied_by: binary_sensor.gpio (dm8-W1-io14)
- gpio: 17
  available: false
  occupied_by: binary_sensor.gpio (dm8-W1-io17)
- gpio: 21
  available: false
  occupied_by: binary_sensor.gpio (dm8-W1-io21)
- gpio: 40
  available: false
  occupied_by: binary_sensor.gpio (dm8-W1-io40)
- gpio: 47
  available: false
  occupied_by: binary_sensor.gpio (dm8-W1-io47)
- gpio: 48
  available: false
  occupied_by: binary_sensor.gpio (dm8-W1-io48)
docs_url: https://devices.esphome.io/devices/KinCony-DM8/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_1
        number: 0
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_1
    name: dm8-input01
- id: binary_sensor_gpio_2
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_1
        number: 1
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_2
    name: dm8-input02
- id: binary_sensor_gpio_3
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_1
        number: 2
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_3
    name: dm8-input03
- id: binary_sensor_gpio_4
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_1
        number: 3
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_4
    name: dm8-input04
- id: binary_sensor_gpio_5
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_1
        number: 4
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_5
    name: dm8-input05
- id: binary_sensor_gpio_6
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_1
        number: 5
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_6
    name: dm8-input06
- id: binary_sensor_gpio_7
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_1
        number: 6
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_7
    name: dm8-input07
- id: binary_sensor_gpio_8
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_1
        number: 7
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_8
    name: dm8-input08
- id: binary_sensor_gpio_9
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 47
        inverted: true
      locked: true
    id: binary_sensor_gpio_9
    name: dm8-W1-io47
- id: binary_sensor_gpio_10
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 48
        inverted: true
      locked: true
    id: binary_sensor_gpio_10
    name: dm8-W1-io48
- id: binary_sensor_gpio_11
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 17
        inverted: true
      locked: true
    id: binary_sensor_gpio_11
    name: dm8-W1-io17
- id: binary_sensor_gpio_12
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 40
        inverted: true
      locked: true
    id: binary_sensor_gpio_12
    name: dm8-W1-io40
- id: binary_sensor_gpio_13
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 13
        inverted: false
      locked: true
    id: binary_sensor_gpio_13
    name: dm8-W1-io13
- id: binary_sensor_gpio_14
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 14
        inverted: false
      locked: true
    id: binary_sensor_gpio_14
    name: dm8-W1-io14
- id: binary_sensor_gpio_15
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 21
        inverted: false
      locked: true
    id: binary_sensor_gpio_15
    name: dm8-W1-io21
- id: display_ssd1306_i2c_1
  component_id: display.ssd1306_i2c
  fields:
    model: SSD1306 128x64
    address: 60
    lambda: 'it.printf(0, 15, id(roboto), "IP: %s", id(eth_ip).state.c_str());'
    id: display_ssd1306_i2c_1
    name: Ssd1306 I2C 1
- id: light_monochromatic_1
  component_id: light.monochromatic
  fields:
    output: dac_ch1_out
    default_transition_length: 0s
    id: light_monochromatic_1
    name: DAC CH1
- id: light_monochromatic_2
  component_id: light.monochromatic
  fields:
    output: dac_ch2_out
    default_transition_length: 0s
    id: light_monochromatic_2
    name: DAC CH2
- id: light_monochromatic_3
  component_id: light.monochromatic
  fields:
    output: dac_ch3_out
    default_transition_length: 0s
    id: light_monochromatic_3
    name: DAC CH3
- id: light_monochromatic_4
  component_id: light.monochromatic
  fields:
    output: dac_ch4_out
    default_transition_length: 0s
    id: light_monochromatic_4
    name: DAC CH4
- id: light_monochromatic_5
  component_id: light.monochromatic
  fields:
    output: dac_ch5_out
    default_transition_length: 0s
    id: light_monochromatic_5
    name: DAC CH5
- id: light_monochromatic_6
  component_id: light.monochromatic
  fields:
    output: dac_ch6_out
    default_transition_length: 0s
    id: light_monochromatic_6
    name: DAC CH6
- id: light_monochromatic_7
  component_id: light.monochromatic
  fields:
    output: dac_ch7_out
    default_transition_length: 0s
    id: light_monochromatic_7
    name: DAC CH7
- id: light_monochromatic_8
  component_id: light.monochromatic
  fields:
    output: dac_ch8_out
    default_transition_length: 0s
    id: light_monochromatic_8
    name: DAC CH8
- id: sensor_ads1115_1
  component_id: sensor.ads1115
  fields:
    multiplexer: A0_GND
    gain: 6.144
    resolution: 16_BITS
    update_interval: 5s
    id: sensor_ads1115_1
    name: ADS1115 Channel A0-GND
- id: sensor_ads1115_2
  component_id: sensor.ads1115
  fields:
    multiplexer: A1_GND
    gain: 6.144
    update_interval: 5s
    id: sensor_ads1115_2
    name: ADS1115 Channel A1-GND
- id: sensor_ads1115_3
  component_id: sensor.ads1115
  fields:
    multiplexer: A2_GND
    gain: 6.144
    update_interval: 5s
    id: sensor_ads1115_3
    name: ADS1115 Channel A2-GND
- id: sensor_ads1115_4
  component_id: sensor.ads1115
  fields:
    multiplexer: A3_GND
    gain: 6.144
    update_interval: 5s
    id: sensor_ads1115_4
    name: ADS1115 Channel A3-GND
- id: switch_uart_1
  component_id: switch.uart
  fields:
    uart_id: uart_1
    id: switch_uart_1
    name: RS485 Button
source:
  type: esphome-devices
  remote_id: KinCony-DM8
  upstream_url: https://github.com/esphome/esphome-devices/blob/main/src/docs/devices/KinCony-DM8/index.md
  upstream_revision: 7fa250835bc3d3a2b319dced285d5e0c27171bd1
  content_hash: d53f41c7a2f2aabe3bfbb1c7e5a495fe47565fa64ac1821728a6828be8acc5d3
