id: kogan_rgb_cool_warm_white_2m_led_strip
name: Kogan RGB + Cool & Warm White 2m LED Strip
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp01_1m
hardware:
  connectivity:
  - wifi
images:
- images/Kogan-RGB-Cool-Warm-White-2m-LED-Strip.jpg
pins:
- gpio: 3
  available: false
  occupied_by: binary_sensor.gpio (${device_name}_button)
- gpio: 4
  available: false
  occupied_by: output.esp8266_pwm (output_red)
- gpio: 5
  available: false
  occupied_by: output.esp8266_pwm (output_coldwhite)
- gpio: 12
  available: false
  occupied_by: output.esp8266_pwm (output_green)
- gpio: 13
  available: false
  occupied_by: output.esp8266_pwm (output_warmwhite)
- gpio: 14
  available: false
  occupied_by: output.esp8266_pwm (output_blue)
docs_url: https://devices.esphome.io/devices/Kogan-RGB-Cool-Warm-White-2m-LED-Strip/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 3
        mode: INPUT_PULLUP
        inverted: true
      locked: true
    id: binary_sensor_gpio_1
    name: Gpio 1
- id: light_rgbww_1
  component_id: light.rgbww
  fields:
    default_transition_length: 0s
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_coldwhite
    warm_white: output_warmwhite
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    id: light_rgbww_1
    name: Rgbww 1
- id: output_esp8266_pwm_1
  component_id: output.esp8266_pwm
  fields:
    pin:
      value: 14
      locked: true
    id: output_esp8266_pwm_1
- id: output_esp8266_pwm_2
  component_id: output.esp8266_pwm
  fields:
    pin:
      value: 12
      locked: true
    id: output_esp8266_pwm_2
- id: output_esp8266_pwm_3
  component_id: output.esp8266_pwm
  fields:
    pin:
      value: 4
      locked: true
    id: output_esp8266_pwm_3
- id: output_esp8266_pwm_4
  component_id: output.esp8266_pwm
  fields:
    pin:
      value: 5
      locked: true
    id: output_esp8266_pwm_4
- id: output_esp8266_pwm_5
  component_id: output.esp8266_pwm
  fields:
    pin:
      value: 13
      locked: true
    id: output_esp8266_pwm_5
source:
  type: esphome-devices
  remote_id: Kogan-RGB-Cool-Warm-White-2m-LED-Strip
  upstream_url: https://github.com/esphome/esphome-devices/blob/main/src/docs/devices/Kogan-RGB-Cool-Warm-White-2m-LED-Strip/index.md
  upstream_revision: 7fa250835bc3d3a2b319dced285d5e0c27171bd1
  content_hash: 72af818b20d19a96e1132af9a7677e8246395a248b0560e2c8a26073a8d1ef98
