id: shelly_plus_1pm_mini
name: Shelly Plus 1PM Mini
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework: esp-idf
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- images/shelly_plus_1pm_mini.png
tags:
- relay
- shelly
pins:
- gpio: 3
  available: false
  occupied_by: sensor.adc (temp_analog_reading)
- gpio: 5
  available: false
  occupied_by: output.gpio (relay_output)
- gpio: 10
  available: false
  occupied_by: binary_sensor.gpio (Switch)
docs_url: https://devices.esphome.io/devices/Shelly-Plus-1PM-Mini/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value: 10
      locked: true
    id: binary_sensor_gpio_1
    name: Switch
- id: light_binary_1
  component_id: light.binary
  fields:
    output: relay_output
    restore_mode: ALWAYS_OFF
    id: light_binary_1
    name: Light
- id: output_gpio_1
  component_id: output.gpio
  fields:
    pin:
      value: 5
      locked: true
    id: output_gpio_1
- id: sensor_ntc_1
  component_id: sensor.ntc
  fields:
    sensor: temp_resistance_reading
    unit_of_measurement: °C
    accuracy_decimals: 1
    icon: mdi:thermometer
    id: sensor_ntc_1
    name: Temperature
- id: sensor_resistance_1
  component_id: sensor.resistance
  fields:
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm
    id: sensor_resistance_1
    name: Resistance 1
- id: sensor_adc_1
  component_id: sensor.adc
  fields:
    pin:
      value: 3
      locked: true
    attenuation: 12db
    id: sensor_adc_1
    name: Adc 1
- id: sensor_bl0942_1
  component_id: sensor.bl0942
  fields:
    uart_id: uart_bus
    update_interval: 5s
    id: sensor_bl0942_1
    name: Bl0942 1
source:
  type: esphome-devices
  remote_id: Shelly-Plus-1PM-Mini
  upstream_url: https://github.com/esphome/esphome-devices/blob/main/src/docs/devices/Shelly-Plus-1PM-Mini/index.md
  upstream_revision: 7fa250835bc3d3a2b319dced285d5e0c27171bd1
  content_hash: 5edc9fee3350bd3463aaca0481ad8397c4524345f8e478f516d866425b46d899
