id: zentec_smart_plug
name: Zentec Smart Plug
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp01_1m
hardware:
  connectivity:
  - wifi
images:
- images/zentec-outside.jpg
- images/zentec-inside.jpg
tags:
- relay
- compact
pins:
- gpio: 4
  available: false
  occupied_by: redLED
- gpio: 12
  available: false
  occupied_by: relay
- gpio: 13
  available: false
  occupied_by: Button
docs_url: https://devices.esphome.io/devices/Zentec-Smart-Plug/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 13
        inverted: true
      locked: true
    internal: false
    id: binary_sensor_gpio_1
    name: Button
- id: relay
  component_id: switch.gpio
  fields:
    pin:
      value: 12
      locked: true
    restore_mode: ALWAYS_OFF
    id: relay
    name: relay
- id: redled
  component_id: switch.gpio
  fields:
    pin:
      value: 4
      locked: true
    inverted:
      value: true
      locked: true
    restore_mode: ALWAYS_ON
    internal: true
    id: redled
    name: redLED
source:
  type: esphome-devices
  remote_id: Zentec-Smart-Plug
  upstream_url: https://github.com/esphome/esphome-devices/blob/main/src/docs/devices/Zentec-Smart-Plug/index.md
  upstream_revision: 2bf64e131a2f72a0fc161c1f2f7d4de85c87a900
  content_hash: 1548c92d08cdfa9762a10ed6c9ac2914a85e83a2c9bea415f73e24d6f2425c1d
